FROM centos:6.7
MAINTAINER Ricardo Borillo <borillo@gmail.com>
MAINTAINER David Rubert <david.rubert@gmail.com>

RUN yum update -y -q && yum install -y -q wget tar gcc python-setuptools python-devel subversion which openssh-clients
RUN yum clean all

# Access keys
RUN mkdir /root/.ssh; chmod 600 /root/.ssh
ADD id_rsa /root/.ssh/id_rsa

# Maven repositories
ADD m2 /root/.m2

# Subversion access
ADD subversion /root/.subversion

# Install pip
RUN easy_install pip

# Install requirements.txt
ADD requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements-centos6.7.txt

# Install Java & Maven
RUN wget -q --no-check-certificate http://ftp.cixug.es/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz -O - | tar zx -C /opt
RUN wget -q --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.tar.gz -O - | tar zx -C /opt
RUN echo export JAVA_HOME=/opt/jdk1.8.0_45 >> /etc/profile.d/java.sh
RUN echo export PATH=$PATH:/opt/apache-maven-3.3.3/bin >> /etc/profile.d/java.sh
ADD mvn /bin/

EXPOSE 5000

VOLUME ["/src"]
WORKDIR /src

ENTRYPOINT ["python", "/src/server.py"]
CMD ["runserver"]
